import js from '@eslint/js';

export default [
    {
        ignores: [
            'vendor',
            'node_modules',
            'public',
            'bootstrap/ssr',
            'tailwind.config.ts',
            'vite.config.ts',
        ],
    },
    js.configs.recommended,
    {
        languageOptions: {
            globals: {
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                fetch: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                HTMLElement: 'readonly',
                HTMLCanvasElement: 'readonly',
                ImageData: 'readonly',
                HTMLImageElement: 'readonly',
                VideoFrame: 'readonly',
                OffscreenCanvas: 'readonly',
                AbortController: 'readonly',
                AbortSignal: 'readonly',
                ReadableStream: 'readonly',
                Response: 'readonly',
                DOMParser: 'readonly',
                TextDecoder: 'readonly',
                TextEncoder: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                CSS: 'readonly',
                getComputedStyle: 'readonly',
                ResizeObserver: 'readonly',
                FormData: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FileList: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                btoa: 'readonly',
                XMLHttpRequest: 'readonly',
                structuredClone: 'readonly',
                queueMicrotask: 'readonly',
                process: 'readonly',
                Buffer: 'readonly',
                setImmediate: 'readonly',
                global: 'readonly',
                self: 'readonly',
                exports: 'readonly',
                module: 'readonly',
                __THREE_DEVTOOLS__: 'readonly',
                WebGLRenderingContext: 'readonly',
                XRWebGLBinding: 'readonly',
                XRWebGLLayer: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLSelectElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                RadioNodeList: 'readonly',
                HTMLCollection: 'readonly',
                Element: 'readonly',
                SVGElement: 'readonly',
                MathMLElement: 'readonly',
                HTMLVideoElement: 'readonly',
                ImageBitmap: 'readonly',
                WorkerGlobalScope: 'readonly',
                performance: 'readonly',
                createImageBitmap: 'readonly',
            },
        },
    },
];
